CREATE TABLE IF NOT EXISTS users (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(255) NOT NULL UNIQUE,
  name varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  description varchar(1000) NOT NULL,
  is_available boolean NOT NULL,
  owner_id int NOT NULL REFERENCES users (id),
  UNIQUE(id, owner_id)
);
